version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/carevision/
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 180
      runas: ubuntu
