spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  data:
    redis:
      host: ${DEV_REDIS_URL}
      port: 6379

elasticsearch:
  uris: ${ES_URIS}
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}