spring:
  application:
    name: CareVision
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  use-fqn: true

openapi:
  secretkey: ${OPENAPI_SECRET_KEY}

jwt:
  refresh-expiration-time: ${REFRESH_EXPIRATION_TIME}
  access-expiration-time: ${ACCESS_EXPIRATION_TIME}
  secret: ${JWT_SECRET_KEY}

camera:
  streaming:
    url: ${CAMERA_STREAMING_URL}
  thumbnail:
    url: ${CAMERA_THUMBNAIL_URL}

firebase:
  secret: ${FIREBASE_SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}